### ISSUE TITLE
TooManyRequestsException

### ISSUE THREAD

**Issue by Kolyall** [ITECOMMPAY/paymentpage-sdk-android#11]
Caused by android.net.ConnectivityManager$TooManyRequestsException:
       at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:3485)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3689)
       at android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:3710)
       at android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:3786)
       at android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:3747)
       at com.paymentpagesdk.core.components.d3s.Core3dsActivity.onCreate(Core3dsActivity.java:140)
       at android.app.Activity.performCreate(Activity.java:8086)
       at android.app.Activity.performCreate(Activity.java:8074)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by Kolyall** [comment]
com.ecommpay:paymentpage-sdk-android:1.16.3
