### ISSUE TITLE
NullPointerException CorePaymentInfo.getActionType()' on a null object reference

### ISSUE THREAD

**Issue by Kolyall** [ITECOMMPAY/paymentpage-sdk-android#12]
implementation "com.ecommpay:paymentpage-sdk-android:1.16.3"

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: 
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.paymentpagesdk.core.CorePaymentInfo$ActionType com.paymentpagesdk.core.CorePaymentInfo.getActionType()' on a null object reference
        at com.paymentpagesdk.core.CoreActivityShow.showResult(CoreActivityShow.kt:70)
        at com.paymentpagesdk.core.CoreActivity.paymentResultWithSuccess(CoreActivity.java:617)
        at com.paymentpagesdk.core.components.presenters.PresenterWithPaymentProcessing$startCheckUpdateTask$1.onSuccess(PresenterWithPaymentProcessing.kt:113)
        at com.paymentpagesdk.core.components.tasks.CheckStatusForPaymentProceedTask.onPostExecute(CheckStatusForPaymentProceedTask.kt:86)
        at com.paymentpagesdk.core.components.tasks.CheckStatusForPaymentProceedTask.onPostExecute(CheckStatusForPaymentProceedTask.kt:14)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by Kolyall** [comment]
implementation "com.ecommpay:paymentpage-sdk-android:1.16.5"


```
 java.lang.NullPointerException: Attempt to invoke virtual method 'com.paymentpagesdk.core.CorePaymentInfo$ActionType com.paymentpagesdk.core.CorePaymentInfo.getActionType()' on a null object reference
        at com.paymentpagesdk.core.CoreActivityShow.showResult(CoreActivityShow.kt:70)
        at com.paymentpagesdk.core.CoreActivity.paymentResultWithSuccess(CoreActivity.java:623)
        at com.paymentpagesdk.core.components.presenters.PresenterWithPaymentProcessing$startCheckUpdateTask$1.onSuccess(PresenterWithPaymentProcessing.kt:113)
        at com.paymentpagesdk.core.components.tasks.CheckStatusForPaymentProceedTask.onPostExecute(CheckStatusForPaymentProceedTask.kt:86)
        at com.paymentpagesdk.core.components.tasks.CheckStatusForPaymentProceedTask.onPostExecute(CheckStatusForPaymentProceedTask.kt:14)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```
