### ISSUE TITLE
FATAL EXCEPTION:  null object reference

### ISSUE THREAD

**Issue by Kolyall** [ITECOMMPAY/paymentpage-sdk-android#8]
// https://mvnrepository.com/artifact/com.ecommpay/paymentpage-sdk-android
implementation group: 'com.ecommpay', name: 'paymentpage-sdk-android', version: '1.14.3'

```
E/AndroidRuntime: FATAL EXCEPTION: main
    
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.paymentpagesdk.core.CorePaymentInfo$ActionType com.paymentpagesdk.core.CorePaymentInfo.getActionType()' on a null object reference
        at com.paymentpagesdk.core.CoreActivityShow.showResult(CoreActivityShow.kt:73)
        at com.paymentpagesdk.core.CoreActivity.paymentResultWithSuccess(CoreActivity.java:573)
        at com.paymentpagesdk.core.components.presenters.PresenterWithPaymentProcessing$startCheckUpdateTask$1.onSuccess(PresenterWithPaymentProcessing.kt:110)
        at com.paymentpagesdk.core.components.tasks.CheckStatusForPaymentProceedTask.onPostExecute(CheckStatusForPaymentProceedTask.kt:84)
        at com.paymentpagesdk.core.components.tasks.CheckStatusForPaymentProceedTask.onPostExecute(CheckStatusForPaymentProceedTask.kt:13)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Comment by Kolyall** [comment]
On real devices - OK.
The bug reproduces only on emulators:
Nexus 5x (API 29)

**Comment by Kolyall** [comment]
To reproduce call:
```
val paymentData = ECMPPaymentInfo(
        projectId = /*my_project_id*/,
        paymentId = "6284bca3f7d048c72ab9604f",
        paymentAmount = 1,
        paymentCurrency = "USD",
        paymentDescription = "account_verification",
        customerId = "6197495697119a0012d9c023_place",
        regionCode = "BY"
    ).apply {
        this.hideSavedWallets = false
        this.languageCode = "ru"
        setAction(ECMPPaymentInfo.ActionType.Verify)
        setRecurrent(
              ECMPRecurrentInfo(
                         type = "U", 
                          expiryDay = "18", 
                          expiryMonth = "05",
                         expiryYear = "2027", 
                         period = null,
                         time = null,
                         startDate = "18-05-2022", 
                         scheduledPaymentID = "6284bd929d2e7c50f587e2bc"
                )
        )
        signature = "xViBbp/eme6TVNvKEJ4RYaQD+/Q/WJBU1zj4NhgoyAu9gW6IZ1Xz6sqzX5lg0m/MWYgoihjlALIxX6gyTDj1Lg=="
    }

val intent = ECMPActivity.buildIntent(context, paymentData)

ActivityCompat.startActivityForResult(
            activity,
            intent,
            PAY_ACTIVITY_REQUEST,
            null
        )
```
